use_frameworks!

target 'ImagePreview_Example' do
  pod 'ImagePreview', :path => '../'

  target 'ImagePreview_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
